
opencost:
  customPricing:
    configPath: /tmp/custom-config
    configmapName: custom-pricing-model
    costModel:
      CPU: 0.0245
      GPU: 0.95
      RAM: 0.0081
      description: Modified pricing configuration.
      internetNetworkEgress: 0.12
      regionNetworkEgress: 0.01
      spotCPU: 0.0245
      spotRAM: 0.0081
      storage: 0.000139
      zoneNetworkEgress: 0.01
    createConfigmap: true
    enabled: true
    provider: custom
  dataRetention:
    dailyResolutionDays: 94
  exporter:
    defaultClusterId: pipeops-altschool
    persistence:
      enabled: true
      size: "50Gi"
      accessMode: "ReadWriteOnce"
  nodeSelector:
    doks.digitalocean.com/node-pool: helper-pool
    kubernetes.io/os: linux
  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090
  tolerations:
  - effect: NoSchedule
    key: managed-by
    operator: Equal
    value: helper-pool
  ui:
    ingress:
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: opencost-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      enabled: true
      hostname: ${host}
      hosts:
      - host: ${host}
        paths:
        - /
      pathType: ImplementationSpecific
      ingressClassName: "nginx"
      servicePort: http-ui
      tls:
        - secretName: opencost-tls
          hosts:
            - ${host}
        
