## If nil, select own namespace. Namespaces to be selected for scrapeConfig discovery.
## If null, exclude the field from the prometheusSpec (keeping downward compatibility with older versions of CRD)
alertmanager:
  alertmanagerSpec:
    tolerations:
    - effect: NoSchedule
      key: managed-by
      operator: Equal
      value: helper-pool
    nodeSelector:
      doks.digitalocean.com/node-pool: helper-pool
      kubernetes.io/os: linux
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kube-alert-manager-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    enabled: true
    hosts:
    - ${alert-manager-host}
    paths:
    - /
    pathType: Prefix
    tls: 
    - hosts:
      - ${alert-manager-host}
      secretName: test-alertmanager-pipeops-dev

grafana:
  additionalDataSources:
    - name: loki
      type: loki
      url: http://grafana-loki-querier:3100
  adminPassword: ${password}
  adminUser: admin
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
    enabled: true
    hosts: 
    - ${kube-grafana-host}
    paths:
    - /
    pathType: Prefix
    tls: 
    - hosts:
      - ${kube-grafana-host}
      secretName: kube-grafana-tls
  persistence:
    enabled: true
    storageClassName: "do-block-storage"
    accessModes:
      - ReadWriteOnce
    size: 30Gi
  nodeSelector:
    doks.digitalocean.com/node-pool: helper-pool
    kubernetes.io/os: linux
  tolerations:
  - effect: NoSchedule
    key: managed-by
    operator: Equal
    value: helper-pool

kube-state-metrics:
  nodeSelector:
    doks.digitalocean.com/node-pool: helper-pool
    kubernetes.io/os: linux
  tolerations:
  - effect: NoSchedule
    key: managed-by
    operator: Equal
    value: helper-pool


prometheus:
  prometheusSpec:
    persistentVolumeClaimRetentionPolicy: 
      whenDeleted: Retain
      whenScaled: Retain
    retention: 94d
    scrapeConfigNamespaceSelector: 
      matchLabels:
        prometheus: ${namespace}
    additionalScrapeConfigs: |
      - job_name: opencost
        honor_labels: true
        scrape_interval: 1m
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        dns_sd_configs:
        - names:
          - opencost.default.svc
          type: 'A'
          port: 9003
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 300Gi
    nodeSelector:
      doks.digitalocean.com/node-pool: helper-pool
      kubernetes.io/os: linux
    tolerations:
    - effect: NoSchedule
      key: managed-by
      operator: Equal
      value: helper-pool
  ingress: 
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kube-prom-auth
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    enabled: true
    hosts:
    - ${kube-prom-host}
    paths:
    - /
    tls:
    - hosts:
      - ${kube-prom-host}
      secretName: kube-prom-tls
prometheusOperator:
  nodeSelector:
    doks.digitalocean.com/node-pool: helper-pool
    kubernetes.io/os: linux
  tolerations:
  - effect: NoSchedule
    key: managed-by
    operator: Equal
    value: helper-pool

prometheus-node-exporter:
  nodeSelector:
    doks.digitalocean.com/node-pool: helper-pool
    kubernetes.io/os: linux
  tolerations:
  - effect: NoSchedule
    key: managed-by
    operator: Equal
    value: helper-pool