extraVolumes:
  - name: service-key-secret
    secret:
      secretName: azure-service-key
opencost: 
  exporter:
    extraVolumeMounts:
      - mountPath: /var/secrets
        name: service-key-secret
  prometheus:
    internal:
      enabled: true
      serviceName: kube-prometheus-stack-prometheus
      namespaceName: monitoring
      port: 9090
  ui:
    ingress:
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/tls-acme: "true"
        kubernetes.io/ingress.class: "nginx"
        ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: opencost-basic-auth
        nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
      enabled: true
      hostname: ${host}
      hosts:
      - host: ${host}
        paths:
        - /
      pathType: ImplementationSpecific
      ingressClassName: "nginx"
      servicePort: http-ui
      tls:
        - secretName: opencost-tls
          hosts:
            - ${host}
        
